# .goreleaser.yml
project_name: dtm
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    id: 'dtm'
    dir: .
    main: ./app/main.go
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}
